-- push_subscriptions 테이블 (channel: 'webpush' | 'fcm' | 'apns')
-- 기존 테이블이 있을 경우 IF NOT EXISTS로 스킵됨

CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  channel text NOT NULL,
  platform text,
  endpoint text,
  device_token text,
  subscription jsonb,
  user_agent text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  last_success_at timestamptz,
  last_error text
);

CREATE UNIQUE INDEX IF NOT EXISTS push_subscriptions_channel_endpoint_uidx
  ON public.push_subscriptions(channel, endpoint)
  WHERE endpoint IS NOT NULL;

ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'push_subscriptions'
      AND policyname = 'users can manage own subscriptions'
  ) THEN
    CREATE POLICY "users can manage own subscriptions"
      ON public.push_subscriptions
      FOR ALL
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;
